spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost}:${MYSQL_PORT:3306}/${MYSQL_SCHEMA:dev}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  profiles:
    include:
      - redis
      - swagger
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
