spring:
  data:
    redis:
      host: acc-redis.u0ldnj.clustercfg.apn2.cache.amazonaws.com
      port: 6379
  datasource:
    url: jdbc:mysql://acc-rds-with-vpc.cfgaqgkoy31u.ap-northeast-2.rds.amazonaws.com:3306/dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: rnfmalelql3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  profiles:
    include:
      - redis
      - swagger
  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${ACCESS_KEY}
        secret-key: ${SECRET_KEY}
      sqs:
        queue-url-like: https://sqs.ap-northeast-2.amazonaws.com/008971650206/GoormySQSForLike
        queue-url-follow: https://sqs.ap-northeast-2.amazonaws.com/008971650206/GoormySQS
      s3:
        bucket: gureumi-photo3
      cloudfront:
        distribution-domain: https://d3ao8a9d2v137r.cloudfront.net

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
